### ISSUE TITLE
No binaries for x86

### ISSUE THREAD

**Issue by techtonik** [cbodley/ms-nfs41-client#1]
I am not sure that many users are able to compile this stuff from source. Is it possible to upload binaries for x86 platform? I am on Vista 32 and binaries from http://www.citi.umich.edu/projects/nfsv4/windows/120612/ are x64 only. =(

**Comment by kofemann** [comment]
Hi, 

You can get the binary from latest code from http://cohortfs.com/windows-nfsv41-client.
The 32 bit builds are not available as client was written for Windows7 x64.

**Comment by techtonik** [comment]
If 32 builds are not available then why there is this code
https://github.com/cbodley/ms-nfs41-client/tree/master/installer.x86 ?

**Comment by cbodley** [comment]
Thanks for pointing that out. I've created a release that includes x86 and x64 installers:
https://github.com/cbodley/ms-nfs41-client/releases/tag/v1.0.0

**Comment by techtonik** [comment]
Thanks. I've installed them, but haven't rebooted yet to test.
